######################## default configuration ####################
baseURL = "https://cepalomares.gitlab.io/web-hugo/"
title = "OfiLibre URJC"
subtitle = "Oficina de Conocimiento y Cultura Libres URJC"
theme = "educenter-hugo"
# post pagination
paginate = "9"
# post excerpt
summaryLength = "10"
# disqus short name
# disqusShortname = "ofilibre" # get your shortname form here : https://disqus.com

# language settings
disableLanguages = [2] # disable language from here
defaultContentLanguage = "es"

# Permalinks settings
[permalinks]
  blog = "/blog/:slug/"

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[[params.plugins.js]]
link = "plugins/fontawesome-icons/all.js"


#################### default parameters ################################
[params]
logo = "images/logo_white.png"
# Meta data
description = "Oficina de Conocimiento y Cultura Libres URJC"
author = "cepalomares"
# contact info
address = "Despacho 004, planta baja edificio Rectorado. C/ Tulipán s/n, 28933 Móstoles (Madrid)"
mobile = "91 488 4679"
email = "ofilibre@urjc.es"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = false

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = true
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "40.338006"
map_longitude = "-3.873924"
map_marker = "images/marker.png" # marker size 37*55 px

# cookies
[params.cookies]
enable = false
expire_days = 1
  
############################# social site ########################
[[params.social]]
title = "twitter"
icon = "fab fa-twitter"
link = "https://twitter.com/OfiLibreURJC"

[[params.social]]
title = "mastodon"
icon = "fab fa-mastodon"
link = "https://floss.social/@OfiLibreURJC"

[[params.social]]
title = "telegram"
icon = "fab fa-telegram-plane"
link = "https://t.me/ofilibreurjc"

[[params.social]]
title = "instagram"
icon = "fab fa-instagram"
link = "https://www.instagram.com/ofilibreurjc/"

[[params.social]]
title = "gitlab"
icon = "fab fa-gitlab"
link = "https://gitlab.etsit.urjc.es/ofilibre"



################################### Idioma espanol #####################################
[Languages.es]
languageName = "Es"
languageCode = "es-es"
contentDir = "content/espanol"
weight = 1
home = "Inicio"
# copyright
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"



################### Navegacion en espanol ####################

# main menu
[[Languages.es.menu.main]]
name = "OfiLibre"
url = "ofilibre"
weight = 1

[[Languages.es.menu.main]]
name = "Blog"
url = "blog"
weight = 2

[[Languages.es.menu.main]]
name = "Eventos"
url = "categories/eventos"
weight = 3

[[Languages.es.menu.main]]
weight = 4
name = "Recursos"
hasChildren = true

  [[Languages.es.menu.main]]
  parent = "Recursos"
  name = "Catálogo de materiales docentes libres"
  url = "catalogo"

  [[Languages.es.menu.main]]
  parent = "Recursos"
  name = "Presentaciones"
  url = "pres"

  [[Languages.es.menu.main]]
  parent = "Recursos"
  name = "Fichas"
  url = "fichas"

  [[Languages.es.menu.main]]
  parent = "Recursos"
  name = "Guías"
  url = "guias"

  [[Languages.es.menu.main]]
  parent = "Recursos"
  name = "OfiLibre Código"
  url = "https://gitlab.etsit.urjc.es/ofilibre/code"

[[Languages.es.menu.main]]
name = "Contacto"
url = "contact"
weight = 5




# footer menu

[[Languages.es.menu.footer]]
name = "Catálogo libre"
url = "catalogo"

[[Languages.es.menu.footer]]
name = "Fichas"
url = "fichas"

[[Languages.es.menu.footer]]
name = "Guías"
url = "guias"

[[Languages.es.menu.footer]]
name = "Presentaciones"
url = "pres"

[[Languages.es.menu.footer]]
name = "OfiLibre Código"
url = "https://gitlab.etsit.urjc.es/ofilibre/code"



################################### English language #####################################
# [Languages.en]
# languageName = "En"
# languageCode = "en-us"
# contentDir = "content/english"
# weight = 2
# home = "Home"
# copyright
# copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"



################### English navigation ####################

# main menu
# [[Languages.en.menu.main]]
# name = "OfiLibre"
# url = "ofilibre"
# weight = 1

# [[Languages.en.menu.main]]
# name = "News"
# url = "blog"
# weight = 2

# [[Languages.en.menu.main]]
# weight = 3
# name = "Resources"
# hasChildren = true

#   [[Languages.en.menu.main]]
#   parent = "Resources"
#   name = "Open catalogue"
#   url = "catalogo"

#   [[Languages.en.menu.main]]
#   parent = "Resources"
#   name = "Presentations"
#   url = "notice"

#   [[Languages.en.menu.main]]
#   parent = "Resources"
#   name = "Software documentation"
#   url = "event"

#   [[Languages.en.menu.main]]
#   parent = "Resources"
#   name = "Guides"
#   url = "scholarship"

#   [[Languages.en.menu.main]]
#   parent = "Resources"
#   name = "OfiLibre Code"
#   url = "research"
  
# [[Languages.en.menu.main]]
# name = "Contact"
# url = "contact"
# weight = 4


# # footer menu

# [[Languages.en.menu.footer]]
# name = "Open Catalogue"
# url = "catalogo"

# [[Languages.en.menu.footer]]
# name = "notice"
# url = "notice"

# [[Languages.en.menu.footer]]
# name = "event"
# url = "event"

# [[Languages.en.menu.footer]]
# name = "scholarship"
# url = "scholarship"

# [[Languages.en.menu.footer]]
# name = "research"
# url = "research"
